### ISSUE TITLE
Map will load on mobile but not on PC

### ISSUE THREAD

**Issue by Highlander211288** [AHAAAAAAA/PokemonGo-Map#3114]
I get a blank, white map when viewing localhost:5000, just the top bar and options dropdown.  I can view the map just fine using my mobile device and ngrok.  PLEASE HELP. :(

**Comment by NickyNice** [comment]
I had this problem, but the exact opposite. It would work on my PC but I was getting the blank white map on my iPhone. The problem ended up being (for whatever reason) the map wouldn't work with iOS 8 so updating to iOS 9 fixed it. What operating system and browser are you using?

**Comment by Harachteh** [comment]
Have you tried using another browser or clicking on refresh (or f5)?

**Comment by noripyon** [comment]
I have exactly the same issue with Highlander211288. It occurs in both Firefox47.0 and Ms Edge 25.1 (windows10) I haven't tried any other browser yet.

F5 didn't solve the problem.

**Comment by Highlander211288** [comment]
I am on Windows 10 and using Chrome.  As dumb as it sounds, the issue was actually resolved by completely clearing my browser history. Probably needed to clear "hosted app data"?  Does anyone know a way to increase the threshold for that?

**Comment by noripyon** [comment]
I still have this issue after clearing browser history both Edge and Firefox. I also tried many things which suggested in #2921 but no luck.

Master version works without any issue.

FYI

**Comment by noripyon** [comment]
I did clean rebuild with latest Node.js and other modules and it works fine now.
Thanks!
