### ISSUE TITLE
DecodeError: Unexpected end-group tag

### ISSUE THREAD

**Issue by yupup** [AHAAAAAAA/PokemonGo-Map#378]
Sometimes after the first loop search, it pops up this error, could be some additional string appended to the end or the start.
Should handle/ignore it instead of just throw exception and exit. 

Exception in thread search_thread:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 599, in main
    pokemonsJSON, ignore, only)
  File "example.py", line 635, in process_step
    profile_response))
  File "example.py", line 413, in get_heartbeat
    m5, )
  File "example.py", line 320, in get_profile
    return retrying_api_req(service, api, access_token, req, useauth=useauth)
  File "example.py", line 208, in retrying_api_req
    **kwargs)
  File "example.py", line 246, in api_req
    p_ret.ParseFromString(r.content)
  File "C:\Python27\lib\site-packages\google\protobuf\message.py", line 186, inParseFromString
    self.MergeFromString(serialized)
  File "C:\Python27\lib\site-packages\google\protobuf\internal\python_message.p", line 844, in MergeFromString
    raise message_mod.DecodeError('Unexpected end-group tag.')
DecodeError: Unexpected end-group tag.

**Comment by Alexkurd** [comment]
Make git pull
it was solved today

**Comment by EstherMartz** [comment]
"[-] retrying_api_req: request error (Unexpected end-group tag.), retrying"

Tried git pull, still appears...

**Comment by mitchelderue** [comment]
I pulled it and still got this issue

**Comment by LeonJansen** [comment]
Servers are overloaded, please try again, it works fine now :)

**Comment by CarlTaylor1989** [comment]
This issue is a server issue, try again when they are up. Closing.
