### ISSUE TITLE
Hitting CTRL+C doesn't stop

### ISSUE THREAD

**Issue by nakami** [AHAAAAAAA/PokemonGo-Map#86]
### Environment info
Operating System:
CentOS 6

Installed version of Python:
2.7

### Description
It seems that since we added threaded=true, there now are multiple threads which needs to be stopped when demanded. Therefore hitting CTRL+C  to stop the script doesn't help. This seems to be a Linux-only problem

### Steps to reproduce
1. Hit CTRL+C while the script is running

### What have you tried?
1. Hitting CTRL+C multiple times, doesn't reliable stop all threads
2. exiting the screen multiplexer if using one (tmux for example): actually works but is ugly

**Comment by DerScreever** [comment]
you could build a worker class. then we can handle multiple threads without problems.
source: http://www.regexprn.com/2010/05/killing-multithreaded-python-programs.html

**Comment by marauder37** [comment]
Code it up and see if it works any better. But I tried an approach like that and it wasn't effective. Using daemon threads sorted it out on most platforms. For linux may I offer `killall -9 python`

**Comment by g3r4n** [comment]
i've got the same issue and now it's good. 
@nakami `git pull` the project and try again.

**Comment by JZ6** [comment]
fixed

**Comment by crckdns** [comment]
Not fixed, had this problem few minutes ago, fresh pull from git. Only kill -9 did help. Killing tmux does the same trick but...that's not intended ;)
